mybatis:
  mapper-locations: classpath:mappers/*.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      fore: true

project:
  properties:
    fcm:
      fireBaseCreateScoped: https://www.googleapis.com/auth/firebase.messaging
      credentialPath: onnuri-4b38d-firebase-adminsdk-jympu-ea1fc6a964.json
      fcmUrl: https://fcm.googleapis.com/v1/projects/onnuri-4b38d/messages:send

xroshot:
  serviceProviderId: ktsaup0347
  serviceProviderPw: new1234!
  sendServerUrl: http://221.148.244.212/catalogs/MAS/recommended/0
  sendFileServierUrl: http://info.xroshot.com/catalogs/FUS-TCSMSG/recommended/0
  endUserId: ktsaup0347
  oneTimeSecretKey: saupblkch1213!
  indexBegin: 300
  version: 1.0.15
  authKey: ${xroshot.indexBegin}
  certFile: OmsqkW1TFuL6mOhhijYR5NzbXRMpXghhgKYb1wGgZFzZaE3wsHOVwei4NvDpTpiQD9mj0shO4FcioLZkVKiSuSTW99ljV3x1pvieCM8FrsjPhi4RTASiFrqCC5dh5JWsNtKIAsGLm3d0fRsTRuVbLzI6Vm6zJ9V32pVNw2lyaQc62WlbmhYUmJH15RB88cK7fLG2f63mvaX1Rid4wj8xZ46vDdd04W0k3X1DWcGJVBYWMZS6c8esC6d3TFW0kIxGgNfhi5OLgu4lexYe7FSGmH7LECUThxl8s6FBUT5RstN5VC4ymvQAyLUXaZDZ8hKm2OfklQETp80MsYsJejfO84bXNrftpjJrhM9mzeKVPxWyVTw5cmz8kUU2BjpAd2HZOwiet04xo3EVKMz09oWcMalOSmPesw7TCRNyda9y1VPdEpruSyziKF80ru14WzEkhCaWQFFp4f1630EcYyjcHcUmKZg7ImOUd3ETYF5S2HgQ142PITkww9O0gJW9UHDTQliai1tvOrYowC0DqueGC8oodd0hR4ZTW73VxphoV7KcBScxYaS8uSJ6vjvwWYWYBuCGa6lJOL94NJwHyDNcNPFmxUjEAmR2MzxKfz0pkYvDWDEHKqporGozF9ZS56uLeuIAyw6OyWSVTUftM7JWbmfQWLXNbrxUZtdTo7ym9v4uK38VbFW9xmAPfXop51JQoVY7MkbmFxmwQDkRp5kISG5JGmH7QuRJvk2VES3Eg6MCtDE22Nj8356BDm2L5CHR05emUYtl6AYNgRImZZAXY8hWUI95teDDsmpHVwtD9seNbVBpeosY2vFyoCANiwgDNSFJIAuybjPHmzjDoyvwiLtxaI07NfWlihpkw6yMOrS1xoucZmYmuNwPNYx5peJaR6F92vkxrlHIaM4IFyQ0SxVD50meoJUSIMJecgUmOgYkfldbStHcNpBIpevdJjykpFmDLWPTbO1xTDe6y8VFiXr65KErwoDKgOffVP7Z7H1GtmAtm6XlcfqUlsaNY0rmvA2A3UPkMbklGM8wX9MXqC5XBzeOxGjhKHCoxZkI0fXjRz7RAmyzJ30IeWgg2KIW4sZDJKLAGUOXA3OqT7qMuBpCrJFqdiI7qIivNBZirw0PoHPZ8xrmg8MBUrL8aGJyQXz6Mgm3fr9AFitmqYH0byMTo8g2JUL0R1HrJZzG759pQRFgrGsCYmL44QAJtyLAG5DPHD44qLwuzEtM0wREai5p2FTilYyHxoAc8s3JR6Wcj1Zvaif2KjFzgKdIox1o4TSV1sWeLJba3NadLD3jSCymUGNec6vGsSRAjR08eNx57d2qSDAZdxc30wSdzeVaTsM3mTz3Q1Px9KEiJaiqpl3vZsGH5lJaV2oSkvcSXTEwCNjv7SPOPqyh3zH8aKKXyMHHF6ILJbAK7yXuzSu7OHaa70hmWaMuSOj4YfXtE8yVX1woqVJU64QOzTks71es6x86o0tqQUYO7EpNbEYfvFhRTXMQl9u28GoYzPUYLfmYdubZ55msfoWYIICjCmWtKzfSkSAuVGmHI99Od1SO53ZM2rZa7hfK7OGSDqJMLmAiuDiiu0qmaIsc3ANGmh0ZSILmu0YbvuBK4p4UdJmoaeGYiamhpvjKLExjWLPVuaPzPEqkuXMgqiZybCEXrMNmNa22gsGqeXHaL9TWw1kLPNzgEHmX3fB4FAP3TXwDWNzwHbO8hL1RDfCCDYZaHmWS7Ib5QrOaSF1VElzPwmd1RPAXCvfZTArImhfqS17XaFEym21hXcICXQNuDFGXuP7dmwVmS4YokJDKdRPLxzcACN0gJvQCIg2gcz8WglmTsKBjU8mzklxxaPe2Bqmuu4jMAUcHoMJ0QyYuNP7hlTx71GktNLM10iu75phXfPcDEViK7TqRN5ElD0bCmb3GS6PywHi6W2D6EUuHyQB5sq0LEafTw6Wi4BQwwfhToKIT5K8gWMIbwENHAT2N0miWFqVQKrau435JMlTq6TEum8DpocLxksWDIULHorPdQ7eRemY71Xtf2EV5Tp4jsLlylHMMocWMSDIS2Fwo4MoGembT3RczyegE39R39ewoqvY66HXdsjm2ITDgQKhzesX6OmVvEmQK3Je8mLNc3QuTCCbqlqKqLRg1gJ3R5tGmuJxGtQTZZRsE44BKap27BdEitZM93X7NXCISwIeTXQm2xuGk0xBVpFEmgg05dlBGi142QUoDf6qGDTxZt87klOqYCjqszOuj7Mgex5mTh2ChXOi11VMFG94s7GYrRr1Vslgc6P7AgT2iAuNXTfUI1Uot69DxbxBNMTVEaoi4TDrjghmhL4TPz02uQdjOeXH2Q9XiKx79rsScu526PZ84b5PM4R0EO0VUV2tkXb3SUpzxa5qGDkqVmGcQr5zHhkAdA1MsvvCqwArfctqk89fYYSsOkPjy2mKXkc9gSMxb3CsrGOvsucUa8CBS6YefTXF6l30rOpaFTkeT1Nyxj4YRFD8UArPWA8wBa2Ie4TNZOaABAUsd4WRPF3o6CeUcihKLOUopR2uAgykog1m2tNVJNUhB8TJdVSuAsL2aYX7qtW3DSUHqZjmQAoMysPrdK2QvAJhRHsg8l36sYotsJCNNqLkDDVOlKZib4ydUI4B9PvsqOfOKAzwWIf7rp4pDjNpzbOHQGyHl7R8eLCyZHpxJyLIbpY74kwklVXRZl3iUt1YHLi7VdSuAFch775J77KhbiPABeDxFSKwv0sdBAXRJSIwsJoByxOMAptPH2I4uacRKHrpuFTsFHRt2jQDRKPbLj2abEtjm4WsWWBUBRW3vLiekpdvUv7qL1RRBPsRxH5LEIHlkRokWZr3gUyJXOQzFe6ssmkH0XcMSYQbEdjYoH2MsNIkekphh70Q20bz6zeWcTmCVVtY0LdA8MOCOX3jKAMMrqxqgL63b0hjMw8jfpDRvSOyNcMHzo9SWd6J7w57Lq6F9mNz84qrZ2tmbV74EJbYJYe4wVtIksXSLhf71UwkIy0oCyFJG0hfeZixbHBVXRSufx0ddztkCBIvbXRFOt3oeq8lVLeNWDRQG9OxSopdxrQKYErBgStLT5gjNr0yxIMRcpcQZOibgV2jBzPMhNiubsNxebqlpMPRPSsUysxwLC9MBmBLActpL5y5viMxSpBDVvJuamUsw3L3CeDWmP7prBamVSqCEmYCQlYUNDKBLPI0I0Bvddj4hh8lC6kUleFmgaEpPBmm9MTLoIQzHjM2VI7KwwAkulhNWVm9l74LZSQVypANvGYFMihgWztyfIieSYM1NuUFajU9qrUAw4hbobv8VpLWSHvUM7ZYPFtXDd4IdWJqtNxsH9FZQNcOEhbbmvyzmLhtlN4HLZBXfDLXqPfW9iCCDc8zUmTqc5VNSQSSkJr598eEjFIdDolmQX3b4o8ojikyKBOjCgpKkzuECxYiamJ7lgT7jaAs0prVYs87yYldLE7dsVXWcCxmHzJ4fmAgKD1wFouEamrh7wWtdQm3mO0UraicsuXx9WSsNLV9WpJxJqC2TacOHKtAE6h8HWD14WqKJEkmHcmwkU7TJRxRLX8YKEmT3glqa4tSwjCYBGcxcTFYtHeiFR4px6AtBXeya8e1lxE2X2KOuF02ZwQPLAe03sVVLic4qvTXU6oXNmD8x0YSMpqamLeoVI1jZGMOI0dSeOfLDmyLOciro1x58BxtQlS0Alp3sOz2cSmAVMmXzRl3894Fp0RpOKhzF3lg3HgVq4eLm9ZzaPW3qkpMfDa9RmHhSxFUog8DXy64kisvgNvpzytiv9Ma4OVQ8ZgzTYqxmmQhL9uhmcYbgkJptr807itZdWa6ECadCNSsEZuTHvbWhizizRkELdAmClZoOUmMhPOPCz2zQbok3RqdPK81KiQ35jrPryffBJQZ3ftof9ddg5Wh5tQ6lyFyXFUCjwUwNQGwF4BHfNiwOiwN5o7DRTmP5mNsi3ajsmXDlXWIVG389qyVxkF2aPDyUDYERtWLT9zMo

---

spring:
  profiles:
     active: dev
  datasource:
     url: jdbc:postgresql://localhost:5432/postgres
     username: postgres
     password: 1234
  main:
    web-application-type: none

logging:
  config: classpath:log4j2_dev.xml
  level:
    root: DEBUG
    org.apache.kafka: WARN
    io: INFO
    org.springframework: INFO
    jdk: INFO
    

netty:
  leakDetection:
    level: PARANOID
---

spring:
  profiles:
     active: stg
  datasource:
     url: jdbc:postgresql://localhost:5432/postgres
     username: postgres
     password: 1234

logging:
  config: classpath:log4j2_stg.xml

netty:
  leakDetection:
    level: PARANOID
---

spring:
  profiles:
     active: prod
  datasource:
     url: jdbc:postgresql://localhost:5432/postgres
     username: postgres
     password: 1234

logging:
  config: classpath:log4j2_prod.xml

netty:
  leakDetection:
    level: SIMPLE

